version: '3.4'

volumes:
  traefik-certificates:

networks:
  traefik-public:
    external: true

services:

  portfolio_webserver:
    build: docker/nginx
    image: robertspektor_nginx
    tty: true
    volumes:
      - ./:/var/www/robertspektor:cached
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`robertspektor.com`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=letsencryptresolver"
